local eq = assert.are.same
local utils = require("buffon.utils")

describe("utils", function()
  it("abbreviate path", function()
    eq(utils.abbreviate_path("/foo/bar/zoo/file.json"), "/f/b/z/file.json")
    eq(utils.abbreviate_path("/foo/bar/[id]/file.json"), "/f/b/[i]/file.json")
    eq(utils.abbreviate_path("/foo/bar/zoo/too/file.json"), "/b/z/t/file.json")
    eq(utils.abbreviate_path("/foo/bar/zoo/too/moo/file.json"), "/z/t/m/file.json")
    eq(utils.abbreviate_path("/foo-boo/file.json"), "/f-b/file.json")
    eq(utils.abbreviate_path("/foo-boo/file-boo.json"), "/f-b/file-boo.json")
  end)

  it("last closed list", function()
    local list = utils.LastClosedList:new(3)
    list:add("/foo/bar1.json")
    list:add("/foo/bar2.json")
    list:add("/foo/bar3.json")
    list:add("/foo/bar4.json")
    eq(#list.buffers, 3)
    eq(list.buffers, { "/foo/bar2.json", "/foo/bar3.json", "/foo/bar4.json" })

    list:add("/foo/bar4.json")
    eq(#list.buffers, 3)
    eq(list.buffers, { "/foo/bar2.json", "/foo/bar3.json", "/foo/bar4.json" })

    eq(list:get_last(), "/foo/bar4.json")
    eq(list:get_last(), "/foo/bar3.json")
    eq(list:get_last(), "/foo/bar2.json")
    eq(list:get_last(), nil)
  end)
end)
